name: 'Build'
on:
  push:
    branches:
      - main

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: docker build -t ghcr.io/davide-almeida/sinatrinha-do-povo:latest .
    - run: docker push ghcr.io/davide-almeida/sinatrinha-do-povo:latest